### ISSUE TITLE
Salwa feedback

### ISSUE THREAD

**Issue by laibaaac** [laibaaac/waffs#1]
code ziet er goed uit, maar waarom de dollar signs? Heel netjes gedaan, is best duidelijk

**Comment by SalwaRingimMohammed** [comment]
Repository review

Netjes gedaan:
- Er staat een live url bij de repo.
- De repo is open voor issues.
- De repo heeft een gitignore.
- De README wordt gebruikt als procesverslag. Vind ik goed gedaan.

Kan beter:
- Er _is_ een repo description, maar het kan beter.
- In de README staat de API niet beschreven.

**Comment by laibaaac** [comment]
heb even mijn readme aangepast!
