### ISSUE TITLE
Feedback van Keisha

### ISSUE THREAD

**Issue by K3A101** [laibaaac/waffs#3]
## Repository
Je repository heeft wel context, alleen zou jij nog bij about, een uitgebreide beschrijving van het project. Er is een README, maar de inhoud kan wat mooier. Dus bij begin van een zin met hoofdletter beginnen enz. 
Je wiki is nog steeds leeg, zet al je proces in de wiki en de korte versie in je readme plaatsen.

Je kan ook uitleggen, hoe je je eigen API heb gemaakt. Dan  kan je het gebruiken voor volgende projecten.

Je moet de live link van de single page op github zetten. 

## Code
Je  code is goed leesbaar en alles is netjes ingesprongen. Zou wel handig zijn als je commentaar toevoegen  bij de functies, zodat jij of iemand anders je code kan begrijpen.

**Comment by laibaaac** [comment]
in about heb ik een uitgebreide beschrijving erbij gezet, Readme is aangepast. 

code heb ik comments toegevoegd!
