### ISSUE TITLE
Review about Javascript

### ISSUE THREAD

**Issue by RainbowJM** [laibaaac/waffs#4]
This function, you can separate it in two.
You will have the function that will only change the data and eventlistener that will do a call, then to another function.
The second function will do the part of random and the return value you will insert in the function of change data.
https://github.com/laibaaac/waffs/blob/411d3fcb3982f6bdff04c1e04f9ca83738bc2fe1/quotes.js#L27-L43

**Comment by laibaaac** [comment]
in mijn modules heb ik het even veranderd!
